library(queuecomputer)
library(ggplot2)
library(dplyr)
set.seed(1)
n <- 100
arrivals_1 <- c(cumsum(rexp(n)),cumsum(rexp(n)))
service_1 <- rexp(2*n, 1/2.5)
queue_1 <- queue_step(arrivals = arrivals_1, service = service_1, servers = 2)
walktimes <- rexp(2*n, 1/100)
arrivals_2 <- lag_step(arrivals = queue_1, service = walktimes)
service_2 <- rexp(2*n, 1/3)
queue_2 <- queue_step(arrivals = arrivals_2, service = service_2, servers = 1)
head(arrivals_1)
head(queue_1$departures_df)
head(arrivals_2)
head(queue_2$departures_df)
summary(queue_1)
summary(queue_2)
